### ISSUE TITLE
Different kind of Titles for the stories

### ISSUE THREAD

**Issue by foucault-dumas** [hestiaAI/data-stories#4]
IMHO:
1) This big block at the bottom is the Title + Lead and should be used like this: 
![image](https://user-images.githubusercontent.com/81250365/152966808-86df5344-6424-4fde-9158-c3c48f174500.png)

2) the "Introduction" block is really optional (need to exist but won't be used often)

![image](https://user-images.githubusercontent.com/81250365/152967021-ac774831-d1dd-44e7-ac63-bdc1a0a1c38b.png)

**Comment by foucault-dumas** [comment]
@pdehaye agreed?
@fquellec I can't asign it to you 🧐

**Comment by pdehaye** [comment]
Agreed with Charles' suggestion of an outcome. But that's going to be a lot of copy paste. 

In my mind some of this - the biio-like information - should also be relevant for "voice" on all kinds of comments. So maybe we should conceive this purple bar as doing two things that should be distinguished better visually (horizontal separation?) and at CMS level (drop downs).

The two things are: introducing who this content is about (person, entity, concept, theme, with name, titles, link to homepage?), which sometimes amounts to voice, and provide a header for the content below.

**Comment by fquellec** [comment]
Hello ! 

Everything is already optional, you can add/remove a paragraph or a profile block or even elements of the profile block. The only thing required is the image in the profileBlock, especially because in my opinion we should have an image that corresponds to each story, in order to share it more nicely and have internal links like below. 

![image](https://user-images.githubusercontent.com/17878016/153170734-01835385-838f-4a73-8501-860681546795.png)

I realise now that this won't always be the case, but it's easy to add a new component that doesn't have an image to answer the `provide a header for the content below` case.

**Comment by pdehaye** [comment]
What would appear as a hover each time there is a signed VoiceBlock?

**Comment by fquellec** [comment]
Okay, so to be clearer about how I see the whole interconnected stories, we have a list of entities (not pages), it could be. : 
- Participants (...)
- Companies (Twitter, Facebook, ...)
- Concepts or **unique story** (SARs, ...)
- Experts from Hestia (Alex, P-O, Charles, ....)

Now for each of these entities we need to define some sort of unified description that must contain at least a name, a description and a photo. 

Once we have done this, we can easily reference each concept, each page and each person throughout the site. It will be useful for easily reuse the ProfileBio, the VoiceBlock and the internal links ( i.e  you want to create a VoiceBlock for P-O, you just enter the text and select the good person and it will automatically set up the right color for P-O and link to his page with a hover preview with the photo and description we previously added for each entity. 
![image](https://user-images.githubusercontent.com/17878016/153368736-4b9c0c81-0652-4c9d-a09a-45f4ad08bbce.png)

We have just defined what happens when you hover over an internal link or a source in the VoiceBlock. But we need to know what happens when it is clicked. For single stories / concepts, it's simple, the link goes to the page itself, but what about people (and maybe companies?) who have multiple pages? For this I propose to make a page per person that list all the stories they have, what do you think ?
