### ISSUE TITLE
Display of arrows

### ISSUE THREAD

**Issue by pdehaye** [hestiaAI/data-stories#58]
Arrows on the left hand side don't always display properly, in particular when loading of the text on the right takes time (e.g. images). Scrolling also contributes to creating problems.

**Comment by fquellec** [comment]
Hello @valentinoli,

As you know, we are currently developing a data story website, you can see it [here](https://data-stories.netlify.app/).
One of the main features is to display a timeline graph next to a text element. In our current implementation, the data stories are a succession of what we call "FlowBlock", defined below. 
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/17878016/155504043-f385b52f-f5e5-42a9-9618-f608f8fa48bc.png">

In order to make links between nodes we use the library [leader-line](https://github.com/anseki/leader-line), it takes to elements in the DOM and draw a line between them, giving a set of options. Right now we have an issue with image loading, when images are loaded in the `content` part, the nodes change position, so we need to update the position of the links by calling `link.position()`on each of them. But I cannot figure out a clean way to do this.. 

If you have an idea, that would be great, and apart from this event problem, feel free to give your opinion on the current implementation of the application. You are much more expert than me in Vue ;)

**Comment by fquellec** [comment]
FIxed in #118
